export enum noteTypes {
	TAP_G,
	TAP_B,
	TAP_R,
	SCR_G_UP,
	SCR_B_UP,
	SCR_G_DOWN,
	SCR_B_DOWN,
	SCR_G_ANYDIR,
	SCR_B_ANYDIR,
	CROSS_B,
	CROSS_C,
	CROSS_G,
	FX_G,
	FX_B,
	FX_R,
	EUPHORIA,
	FS_SAMPLES,
	FS_CROSS,
	SCR_G_ZONE = 20,
	SCR_B_ZONE,
	FX_ALL,
	CROSS_FORCE_CENTER,
	BATTLE_PLAYER_SWITCH = 26,
	CF_SPIKE_G,
	CF_SPIKE_B,
	CF_SPIKE_C,
	MEGAMIX_TRANSITION,
	FS_CROSS_GREEN_MARKER,
	FS_CROSS_BLUE_MARKER,
	FX_TYPE_FILTER = 0x05ffffff,
	FX_TYPE_BEATROLL,
	FX_TYPE_BITREDUCTION,
	FX_TYPE_WAHWAH,
	FX_TYPE_RINGMOD,
	FX_TYPE_STUTTER,
	FX_TYPE_FLANGER,
	FX_TYPE_ROBOT,
	FX_TYPE_BEATROLLAUTO,
	FX_TYPE_DELAY = 0x60000009,
	STRING_DATA = 0xafffffff,
	BPM_FAKE_DISTANCE = 0x0b000001,
	BPM,
	REWIND_CHECKPOINT = 0x09ffffff
}

export interface noteData {
	type: noteTypes
	time: number
	lane: number
	length: number
	extra: number
}
